version: '2'
services:
  db:
    image: mysql:5.7
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: railsapp
      MYSQL_USER: userailsapp
      MYSQL_PASSWORD: password
    ports:
      - 3307:3306
  app:
    build: ./ruby
    volumes:
      - ./myrailsapp/:/myrailsapp
      - ./config:/config
    command: 
      - /config/newrailapp_newdb.sh
      # - /config/existapp_newdb.sh
    ports:
      - 3001:3000      
    depends_on:
      - db
    links:
      - db
    environment:
      DB_USER: root
      DB_NAME: railsapp
      DB_PASSWORD: password
      DB_HOST: db
      APP_ROOT: /myrailsapp
